fullnameOverride: jackett
image:
  replicaCount: 1
  repository: linuxserver/jackett
  tag: "latest"
  pullPolicy: Always
  containerPort: 9117
  hostname: jackett
  domainPath: "UI"
  # domainPath: "indexer"
  # stripPath: true
  env:
    - name: TZ
      value: UTC
    - name: PGID
      value: "1000"
    - name: PUID
      value: "1000"
  volumes:
    configPath: /config
    configCapacity: 10Mi
    storageClassName: nfs-client
    downloadsPath: /downloads
    downloadsClaim: downloads-claim

service:
  type: ClusterIP
  
serviceAccount:
  create: true
  annotations: {}
  name: "jackett"
  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80