apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include ".helm.fullname" . }}-startup"
data:
  config.ini: |
    [general]
    base_url = /bazarr

    [sonarr]
    ip = sonarr
    port = 8989
    base_url = /sonarr

    [radarr]
    ip = radarr
    port = 7878
    base_url = /radarr

    [postgresql]
    enabled = False
    host = localhost
    port = 5432
    database = {{ .Values.postgres.DATABASE_NAME }}
    username = {{ .Values.postgres.DATABASE_USER }}
    password = {{ .Values.postgres.DATABASE_PASSWORD }}
