# https://wiki.servarr.com/radarr/postgres-setup
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include ".helm.fullname" . }}-startup"
data:
  config.xml: |
    <Config>
      <UrlBase>/radarr</UrlBase>
      <PostgresUser>{{ .Values.global.postgresUser }}</PostgresUser> 
      <PostgresPassword>{{ .Values.global.postgresPassword }}</PostgresPassword>
      <PostgresPort>5432</PostgresPort>    
      <PostgresHost>postgres</PostgresHost>      
      <PostgresMainDb>{{ .Values.global.radarrMainDb }}</PostgresMainDb>
      <PostgresLogDb>{{ .Values.global.radarrLogDb }}</PostgresLogDb>
    </Config>