image:
  repository: linuxserver/radarr
  tag: "latest"
  pullPolicy: Always
  containerPort: 7878
  hostname: radarr
  # env:
  #   - name: TZ
  #     value: UTC
  #   - name: PGID
  #     value: "0"
  #   - name: PUID
  #     value: "0"

service:
  type: ClusterIP

serviceAccount:
  create: true
  annotations: {}
  name: "radarr"