image:
  repository: lscr.io/linuxserver/radarr
  tag: "latest"
  pullPolicy: Always
  containerPort: 7878
  hostname: radarr
  # env:
  #   - name: TZ
  #     value: UTC
  #   - name: PGID
  #     value: "0"
  #   - name: PUID
  #     value: "0"

config:
  UrlBase: /radarr
  PostgresPort: 5432
  PostgresHost: postgres
  LogLevel: info
  UpdateMechanism: Docker
  BindAddress: "*"
  Port: 7878
  SslPort: 9898
  EnableSsl: False
  LaunchBrowser: True
  AuthenticationMethod: None
  Branch: master
  SslCertPath: 
  SslCertPassword: 
  InstanceName: Radarr

service:
  type: ClusterIP

serviceAccount:
  create: true
  annotations: {}
  name: "radarr"