apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-{{ include ".helm.fullname" . }}-secret"
data:
  DATABASE_PASSWORD: {{ .Values.postgres.DATABASE_PASSWORD | b64enc }}
stringData:
  DATABASE_NAME: {{ .Values.global.bwDb }}
  DATABASE_USER: {{ .Values.postgres.DATABASE_USER }}
  BW_DOMAIN: {{ .Values.BW_DOMAIN }}
  BW_DB_PROVIDER: postgresql