image:
  repository: lscr.io/linuxserver/readarr
  tag: "develop"
  pullPolicy: Always
  containerPort: 8787
  hostname: readarr
  # env:
  #   - name: TZ
  #     value: UTC
  #   - name: PGID
  #     value: "0"
  #   - name: PUID
  #     value: "0"

config:
  UrlBase: /readarr
  LogLevel: info
  UpdateMechanism: Docker
  BindAddress: "*"
  Port: 8787
  SslPort: 6868
  EnableSsl: False
  LaunchBrowser: True
  AuthenticationMethod: None
  Branch: develop
  SslCertPath: 
  SslCertPassword: 
  InstanceName: Readarr

service:
  type: ClusterIP

serviceAccount:
  create: true
  annotations: {}
  name: "readarr"