fullnameOverride: transmission
image:
  replicaCount: 1
  repository: linuxserver/transmission
  tag: "latest"
  pullPolicy: Always
  containerPort: 9091
  hostname: transmission
  domainPath: "downloads"
  stripPath: true
  env:
    - name: TZ
      value: UTC
    - name: PGID
      value: 0
    - name: PUID
      value: 0
    - name: TRANSMISSION_WEB_HOME
      value: "/kettu/"
  volumes:
    storageClassName: nfs-client
    configPath: /config
    configCapacity: 10Mi
    downloadsPath: /downloads
    downloadsClaim: downloads-claim

serviceAccount:
  create: true
  annotations: {}
  name: "transmission"
  
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80