apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ include ".helm.fullname" . }}-route"
spec:
  entryPoints:
    - web
  routes:
    - match: (PathPrefix("/transmission","/download","/downloads") || PathPrefix("/transmission/web","/transmission/rpc"))
      kind: Rule
      services:
        - name: {{ include ".helm.fullname" . }}
          kind: Service
          port: {{ .Values.image.containerPort }}