apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-vpn-secret"
data:
  OPENVPN_PASSWORD: {{ .Values.vpn.password | b64enc }}
  TRANSMISSION_RPC_PASSWORD: {{ .Values.password | b64enc }}
stringData:
  OPENVPN_USERNAME: {{ .Values.vpn.username }}
  TRANSMISSION_RPC_USERNAME: {{ .Values.username }}
