apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".helm.fullname" . }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        date: "{{ now | unixEpoch }}"
        {{- include ".helm.selectorLabels" . | nindent 8 }}
    spec:
      hostname: {{ .Values.image.hostname }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include ".helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: prep-postgres
        image: ghcr.io/xander-rudolph/postgres-prep:latest
        envFrom:
          - configMapRef:
              name: "postgres-configmap"
          - secretRef:
              name: "postgres-secret"
          - secretRef:
              name: "{{ include ".helm.fullname" . }}-secret"
      containers:
        - name: {{ include ".helm.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
          {{- if .Values.image.env }}
            {{- toYaml .Values.image.env | nindent 12 }}
          {{- end }}
            - name: BW_DOMAIN
              value: {{ .Values.BW_DOMAIN }}
            - name: BW_DB_PROVIDER
              value: postgresql
            - name: BW_DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: "{{ include ".helm.fullname" . }}-secret"
                  key: DATABASE_NAME        
            - name: BW_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ include ".helm.fullname" . }}-secret"
                  key: DATABASE_USER        
            - name: BW_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ include ".helm.fullname" . }}-secret"
                  key: DATABASE_PASSWORD        
            - name: BW_DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_HOSTNAME
          # envFrom: N/A
          args: [ {{.Values.image.args}} ]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
