image:
  repository: lscr.io/linuxserver/lidarr
  tag: "latest"
  pullPolicy: Always
  containerPort: 8686
  hostname: lidarr
  # env:
  #   - name: TZ
  #     value: UTC
  #   - name: PGID
  #     value: "0"
  #   - name: PUID
  #     value: "0"

config:
  UrlBase: /lidarr
  LogLevel: info
  UpdateMechanism: Docker
  BindAddress: "*"
  Port: 8686
  SslPort: 6868
  EnableSsl: False
  LaunchBrowser: True
  AuthenticationMethod: None
  Branch: master
  SslCertPath: 
  SslCertPassword: 
  InstanceName: Lidarr

service:
  type: ClusterIP

serviceAccount:
  create: true
  annotations: {}
  name: "lidarr"