redis:
  hostname: redis
  repository: redis
  tag: latest
  pullPolicy: Always
  containerPort: 6379
  mountPath: /data

service:
  type: ClusterIP

serviceAccount:
  create: true
  annotations: {}
  name: "redis"
