image:
  repository: lscr.io/linuxserver/sonarr
  tag: "latest"
  pullPolicy: Always
  containerPort: 8989
  hostname: sonarr
  # env:
  #   - name: TZ
  #     value: UTC
  #   - name: PGID
  #     value: "0"
  #   - name: PUID
  #     value: "0"

config:
  UrlBase: /sonarr
  LogLevel: info
  UpdateMechanism: Docker
  BindAddress: "*"
  Port: 8989
  SslPort: 9898
  EnableSsl: False
  LaunchBrowser: True
  AuthenticationMethod: None
  Branch: main
  SslCertHash: 
  InstanceName: Sonarr
  SyslogPort: 514

service:
  type: ClusterIP

serviceAccount:
  create: true
  annotations: {}
  name: "sonarr"