fullnameOverride: sonarr
image:
  replicaCount: 1
  repository: linuxserver/sonarr
  tag: "latest"
  pullPolicy: Always
  containerPort: 8989
  hostname: sonarr
  domainPath: "tv"
  stripPath: true
  env:
    - name: TZ
      value: UTC
    - name: PGID
      value: 0
    - name: PUID
      value: 0
  volumes:
    storageClassName: nfs-client
    configPath: /config
    configCapacity: 10Mi
    tvPath: /tv
    tvClaim: tv-claim
    downloadsPath: /downloads
    downloadsClaim: downloads-claim

serviceAccount:
  create: true
  annotations: {}
  name: "sonarr"
  
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80