apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include ".helm.selectorLabels" . | nindent 8 }}
    spec:
      hostname: {{ .Values.redis.hostname }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include ".helm.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.redis.repository }}:{{ .Values.redis.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.redis.pullPolicy }}
          env: 
            {{- toYaml .Values.redis.env | nindent 12 }}
          args: [ {{.Values.redis.args}} ]
          ports:
            - name: http
              containerPort: {{ .Values.redis.containerPort }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: "{{ include ".helm.fullname" . }}-secret"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: redis-vol
            mountPath: {{ .Values.redis.mountPath }}
      volumes:
        - name: redis-vol
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ include ".helm.fullname" . }}-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
