apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-{{ include ".helm.fullname" . }}-secret"
data:
  TOKEN: {{ .Values.token | b64enc }}
stringData:
  SUBDOMAINS: {{ .Values.subdomains }}
