apiVersion: v2
name: media-kube
description: A Helm chart for transmission deployed behind a traefik ingress
type: application
version: 1.0.0
appVersion: "0.0.1"
dependencies:
  - name: traefik
    version: "^10.24.2"
    repository: https://helm.traefik.io/traefik
  - name: duckdns
    version: "^0"
    repository: "file://./charts/duckdns"
  - name: lidarr
    version: "^0"
    repository: "file://./charts/lidarr"
  - name: ombi
    # TODO: need to fix the ingress
    version: "^0"
    repository: "file://./charts/ombi"
  - name: overseerr
    version: "^0"
    repository: "file://./charts/overseerr"
  - name: prowlarr
    version: "^0"
    repository: "file://./charts/prowlarr"
  - name: radarr
    version: "^0"
    repository: "file://./charts/radarr"
  - name: readarr
    version: "^0"
    repository: "file://./charts/readarr"
  - name: requestrr
    version: "^0"
    repository: "file://./charts/requestrr"
  - name: sonarr
    version: "^0"
    repository: "file://./charts/sonarr"
  - name: transmission
    version: "^0"
    repository: "file://./charts/transmission"
  # - name: jackett
  #   version: "^0"
  #   repository: "file://./charts/jackett"
  # - name: lazylibrarian
  #   version: "^0"
  #   repository: "file://./charts/lazylibrarian"
