apiVersion: v2
name: mediakube
description: A Helm chart for transmission deployed behind a traefik ingress
type: application
version: 1.0.0
appVersion: "0.0.1"
dependencies:
  - name: traefik
    version: "^10.24.2"
    repository: https://helm.traefik.io/traefik
  - name: authelia
    version: "^0.8.57"
    repository: https://charts.authelia.com
  - name: duckdns
    version: "^0"
    repository: "file://./charts/duckdns"
  - name: lidarr
    version: "^0"
    repository: "file://./charts/lidarr"
  - name: ombi
    version: "^0"
    repository: "file://./charts/ombi"
  - name: postgresql
    version: "^0"
    repository: "file://./charts/postgresql"
  - name: prowlarr
    version: "^0"
    repository: "file://./charts/prowlarr"
  - name: radarr
    version: "^0"
    repository: "file://./charts/radarr"
  - name: readarr
    version: "^0"
    repository: "file://./charts/readarr"
  - name: sonarr
    version: "^0"
    repository: "file://./charts/sonarr"
  - name: bazarr
    version: "^0"
    repository: "file://./charts/bazarr"
  # - name: requestrr
  #   version: "^0"
  #   repository: "file://./charts/requestrr"
  # - name: transmission
  #   version: "^0"
  #   repository: "file://./charts/transmission"
