storage:
  storageClassName: nfs-client 
  capacityMedia: 1024Gi
  capacityConfig: 5Gi

enableTraefikDashboard: true

# https://artifacthub.io/packages/helm/supertetelman/nfs-client-provisioner
nfs-client-provisioner:
  name: nfs-client
  storageClass:
    accessModes: ReadWriteMany
    defaultClass: false # this might be worth it
  nfs:
    server: 192.168.1.9
    path: /Media
    # mountOptions: ReadWriteMany

# https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
nfs-subdir-external-provisioner:
    nfs:
      server: 192.168.1.9
      path: /Media

jackett:
  image:
    volumes:
      configPath: /mnt/e/docker/jackett
