debug:
  useLocalStore: true
  mediaCapacity: 100Gi

#################
# Global config #
#################
global:
  nfs:
    server: YOUR_NFS_SERVER
  configPath: YOUR_CONFIG_PATH
  configCapacity: 10Gi # each service will be allocated the same capacity. Divide the total config capacity by 6 (or the number of services that will be deployed)
  hostPath: "YOUR_LOCAL_STORAGE" # use this path localized storage
  mediaPath: YOUR_MEDIA_PATH
  mediaCapacity: 15Ti
  # linuxserver common variables
  timezone: Etc/UTC
  PGID: 0
  PUID: 0
  postgresUser: "postgres"
  postgresPassword: "YOUR_POSTGRES_PASSWORD"
  radarrMainDb: radarrmain
  radarrLogDb: radarrlog


##################
# Network config #
##################
enableTraefikDashboard: true
creds:
  user: administrator
  password: Dashboard

duckdns:
  fullnameOverride: duckdns
  subdomains: YOUR_SUBDOMAINS
  token: YOUR_DNS_TOKEN

# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml  
traefik:
  image:
    pullPolicy: Always
  service:
    type: LoadBalancer

########################################
# Service config - local disk required #
########################################
# this section forces use of local storage because of issues with the NFS not allowing startup because it tries to chmod
ombi:
  # Use configPath for NFS... permission issues with nfs creation though
  # configPath: ombi
  # Use hostPath for local storage
  hostPath: ombi
  fullnameOverride: ombi

postgresql:
  # Use configPath for NFS... permission issues with nfs creation though
  # configPath: postgres
  # Use hostPath for local storage
  hostPath: postgres
  fullnameOverride: postgres

#######################################
# Service config - NFS mount required #
#######################################
lidarr:
  # configPath: lidarr
  hostPath: lidarr
  fullnameOverride: lidarr

prowlarr:
  # configPath: prowlarr
  hostPath: prowlarr
  fullnameOverride: prowlarr

radarr:
  # configPath: radarr
  hostPath: radarr
  fullnameOverride: radarr

readarr:
  # configPath: readarr
  hostPath: readarr
  fullnameOverride: readarr

requestrr:
  # configPath: requestrr
  hostPath: requestrr
  fullnameOverride: requestrr

sonarr:
  # configPath: sonarr
  hostPath: sonarr
  fullnameOverride: sonarr

transmission:
  # configPath: transmission
  hostPath: transmission
  fullnameOverride: transmission
  username: YOUR_USERNAME
  password: YOUR_PASSWORD
  vpn:
    username: YOUR_PIA_USERNAME
    password: YOUR_PIA_PASSWORD
