debug:
  # this will only set media to the local storage
  useLocalStore: false
  mediaCapacity: 100Gi

#################
# Global config #
#################
global:
  #################
  # NFS config #
  #################
  # This section is needed to use NFS for storage
  nfs:
    server: YOUR_NFS_SERVER
  mediaPath: YOUR_MEDIA_PATH
  mediaCapacity: 15Ti # total capacity of your NFS media share (unless you want a buffer)

  # # This section is a bit problematic because some apps don't behave well or throw permission errors for NFS storage
  # # nfs config path
  # configPath: YOUR_CONFIG_PATH
  
  #################
  # Local config #
  #################
  # local storage path such as /mnt/d/kubestore
  hostPath: "YOUR_LOCAL_STORAGE" # use this path localized storage
  configCapacity: 10Gi # each service will be allocated the same capacity. Divide the total config capacity by the number of services that will be deployed

  ################################
  # linuxserver common variables #
  ################################
  timezone: Etc/UTC
  PGID: 0
  PUID: 0

  ######################
  # postgres variables #
  ######################
  postgresUser: "postgres"
  postgresPassword: "YOUR_POSTGRES_PASSWORD"

  ###################
  # redis variables #
  ###################
  redisUser: "redis"
  redisPassword: "YOUR_REDIS_PASSWORD"

  ###################
  # other variables #
  ###################
  radarrMainDb: radarrmain
  radarrLogDb: radarrlog
  bazarrDb: bazarr
  URL: yourdomain.url
  radarrKey: YOUR_RADARR_KEY
  sonarrKey: YOUR_SONARR_KEY

##################
# Network config #
##################
enableTraefikDashboard: true
creds:
  user: administrator
  password: Dashboard

duckdns:
  fullnameOverride: duckdns
  subdomains: YOUR_SUBDOMAINS
  token: YOUR_DNS_TOKEN

swag:
  hostPath: swag
  fullnameOverride: swag

# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml  
traefik:
  image:
    pullPolicy: Always
  service:
    type: LoadBalancer
  providers:
    kubernetesCRD:
      allowCrossNamespace: true

#########################
# Authentication config #
#########################
# https://github.com/authelia/chartrepo/blob/master/charts/authelia/values.yaml
authelia:
  #TODO: no idea what this actually does... it creates the allowed ingress traffic but I don't think I wired it up right
  networkPolicy:
    enabled: true
  persistence:
    enabled: true
    size: 10Gi
  secret:
    #TODO: I think this needs to be managed in order to prevent needing a clean postgres DB each time
    storageEncryptionKey:
      value: "YOUR_ENCRYPTION_KEY" # Must be 20 characters long
    storage:
      value: YOUR_AUTHELIA_DBPASSWORD
    redis:
      value: YOUR_REDIS_PASSWORD
  configMap:
    notifier:
      smtp:
        enabled: false
      filesystem:
        enabled: true        
    authentication_backend:
      ldap:
        enabled: false
      file:
        enabled: true
    session:
      redis:
        host: redis
        enabled: true
        enabledSecret: true
    storage: 
      postgres:
        enabled: true
        host: postgres
        port: 5432
        database: YOUR_AUTHELIA_DBNAME
        schema: public
        username: YOUR_AUTHELIA_DBUSERNAME
        timeout: 5s
        tls:
          enabled: false
          skip_verify: true
  ingress:
    enabled: true
    tls:
      enabled: true
      secret: authelia-tls
    traefikCRD:
      entryPoints:
      - web
      - websecure
      enabled: true 
      matchOverride: (Host("yourdomain.url") || Host("localhost")) && PathPrefix("/")
      middlewares:
        auth:
          nameOverride: authelia-auth
          authResponseHeaders:
          - Remote-User
          - Remote-Name
          - Remote-Email
          - Remote-Groups
        chains:
          auth:
            nameOverride: authelia-auth-chain
            # List of Middlewares to apply before the forwardAuth Middleware in the authentication chain.
            before: []
            # before:
            # - name: extra-middleware-name
            #   namespace: default
            # List of Middlewares to apply after the forwardAuth Middleware in the authentication chain.
            after: []
            # after:
            # - name: extra-middleware-name
            #   namespace: default
          ingressRoute:
            # List of Middlewares to apply before the middleware in the IngressRoute chain.
            before: []
            # before:
            # - name: extra-middleware-name
            #   namespace: default
            # List of Middlewares to apply after the middleware in the IngressRoute chain.
            after: []
            # after:
            # - name: extra-middleware-name
            #   namespace: default

postgresql:
  hostPath: postgres
  fullnameOverride: postgres
  # # optional
  # configPath: postgres

redis:
  hostPath: redis
  fullnameOverride: redis
  # # optional
  # configPath: redis

####################
# Media app config #
####################
ombi:
  hostPath: ombi
  fullnameOverride: ombi
  # # optional
  # configPath: ombi

sonarr:
  hostPath: sonarr
  fullnameOverride: sonarr
  # # optional
  # configPath: sonarr
  # config:
  #   UrlBase: /sonarr
  #   PostgresPort: 5432
  #   PostgresHost: postgres
  #   LogLevel: info
  #   UpdateMechanism: Docker
  #   BindAddress: "*"
  #   Port: 8989
  #   SslPort: 9898
  #   EnableSsl: False
  #   LaunchBrowser: True
  #   AuthenticationMethod: None
  #   Branch: main
  #   SslCertHash: 
  #   InstanceName: Sonarr
  #   SyslogPort: 514

prowlarr:
  hostPath: prowlarr # use only one... host or config
  fullnameOverride: prowlarr
  # # optional
  # configPath: prowlarr # use only one... host or config
  # config:
  #   UrlBase: /prowlarr
  #   LogLevel: info
  #   UpdateMechanism: Docker
  #   BindAddress: "*"
  #   Port: 9696
  #   SslPort: 6969
  #   EnableSsl: False
  #   LaunchBrowser: True
  #   AuthenticationMethod: None
  #   Branch: master
  #   SslCertPath: 
  #   SslCertPassword: 
  #   InstanceName: Prowlarr

radarr:
  hostPath: radarr # use only one... host or config
  fullnameOverride: radarr
  postgres:
    DATABASE_NAME: "radarr"
    DATABASE_USER: "radarr"
    DATABASE_PASSWORD: "YOUR_RADARR_DBPASS"
  # # optional
  # configPath: radarr 
  # config:
  #   UrlBase: /radarr
  #   PostgresPort: 5432
  #   PostgresHost: postgres
  #   LogLevel: info
  #   UpdateMechanism: Docker
  #   BindAddress: "*"
  #   Port: 7878
  #   SslPort: 9898
  #   EnableSsl: False
  #   LaunchBrowser: True
  #   AuthenticationMethod: None
  #   Branch: master
  #   SslCertPath: 
  #   SslCertPassword: 
  #   InstanceName: Radarr

lidarr:
  hostPath: lidarr # use only one... host or config
  fullnameOverride: lidarr
  # # optional
  # configPath: lidarr 
  # config:
  #   UrlBase: /lidarr
  #   LogLevel: info
  #   UpdateMechanism: Docker
  #   BindAddress: "*"
  #   Port: 8686
  #   SslPort: 6868
  #   EnableSsl: False
  #   LaunchBrowser: True
  #   AuthenticationMethod: None
  #   Branch: master
  #   SslCertPath: 
  #   SslCertPassword: 
  #   InstanceName: Lidarr

readarr:
  hostPath: readarr # use only one... host or config
  fullnameOverride: readarr
  # # optional
  # configPath: readarr 
  # config:
  #   UrlBase: /readarr
  #   LogLevel: info
  #   UpdateMechanism: Docker
  #   BindAddress: "*"
  #   Port: 8787
  #   SslPort: 6868
  #   EnableSsl: False
  #   LaunchBrowser: True
  #   AuthenticationMethod: None
  #   Branch: develop
  #   SslCertPath: 
  #   SslCertPassword: 
  #   InstanceName: Readarr

bazarr:
  hostPath: bazarr # use only one... host or config
  fullnameOverride: bazarr
  postgres:
    DATABASE_NAME: "bazarr"
    DATABASE_USER: "bazarr"
    DATABASE_PASSWORD: "YOUR_BAZARR_DBPASS"
  # # optional
  # configPath: bazarr
  # config:
  #   UrlBase: /bazarr
  #   LogLevel: info
  #   UpdateMechanism: Docker
  #   BindAddress: "*"
  #   Port: 6767
  #   SslPort: 6868
  #   EnableSsl: False
  #   LaunchBrowser: True
  #   AuthenticationMethod: None
  #   Branch: develop
  #   SslCertPath: 
  #   SslCertPassword: 
  #   InstanceName: bazarr

transmission:
  hostPath: transmission
  fullnameOverride: transmission
  username: YOUR_USERNAME
  password: YOUR_PASSWORD
  vpn:
    username: YOUR_VPN_USERNAME
    password: YOUR_VPN_PASSWORD
    LOC: YOUR_VPN_REGION # EX https://serverlist.piaservers.net/vpninfo/servers/v6
  # # optional  
  # configPath: transmission

############################################
# Disabled due to concerns around security #
############################################
# requestrr:
#   hostPath: requestrr # use only one... host or config
#   fullnameOverride: requestrr
#   config:
#     discordAppId: YOUR_DISCORD_APPID
#     discordBotToken: YOUR_DISCORD_BOTTOKEN
#     # optional
#     UrlBase: /requestrr
#     Port: 4545
#     ombi: ombi
#     sonarr: sonarr
#     radarr: radarr