# https://github.com/bitwarden/server/blob/master/docker-unified/settings.env
image:
  repository: bitwarden/server
  tag: "latest"
  pullPolicy: Always
  hostname: bitwarden

BW_DOMAIN: bitwarden.yourdomain.com

service:
  type: ClusterIP

serviceAccount:
  create: true
  annotations: {}
  name: "bitwarden"

postgres:
  DATABASE_NAME: "bitwarden_vault"
  DATABASE_USER: "warden"
  DATABASE_PASSWORD: "bitwarden"