apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include ".helm.fullname" . }}-configmap"
data:
  POSTGRES_DB: {{ .Values.postgres.db }}
  POSTGRES_PORT: "{{ .Values.postgres.containerPort }}"
  POSTGRES_HOSTNAME: {{ include ".helm.fullname" . }}
