apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include ".helm.selectorLabels" . | nindent 8 }}
    spec:
      hostname: {{ .Values.postgres.hostname }}
      {{- if .Values.serviceAccount.create -}}
      serviceAccountName: {{ include ".helm.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.postgres.repository }}:{{ .Values.postgres.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.postgres.pullPolicy }}
          env: 
            {{- toYaml .Values.postgres.env | nindent 12 }}
          args: [ {{.Values.postgres.args}} ]
          ports:
            - name: http
              containerPort: {{ .Values.postgres.containerPort }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: "{{ include ".helm.fullname" . }}-secret"
            - configMapRef:
                name: "{{ include ".helm.fullname" . }}-configmap"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: postgres-vol
            mountPath: {{ .Values.postgres.mountPath }}
          {{- if .Values.startUp }}
          - name: file-config
            mountPath: /docker-entrypoint-initdb.d
          {{- end }}
      volumes:
        - name: postgres-vol
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ include ".helm.fullname" . }}-pvc
        {{- if .Values.startUp }}
        - name: file-config
          configMap:
            name: "{{ include ".helm.fullname" . }}-startup"
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
