apiVersion: v1
kind: Secret
metadata:
  name: "{{ include ".helm.fullname" . }}-secret"
data:
  {{- if .Values.global.postgresPassword }}
  POSTGRES_PASSWORD: {{ .Values.global.postgresPassword | b64enc }}
  {{- else }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
  {{- end }}
stringData:
  {{- if .Values.global.postgresUser }}
  POSTGRES_USER: {{ .Values.global.postgresUser }}
  {{- else }}
  POSTGRES_USER: {{ .Values.postgres.user }}
  {{- end }}
  