apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include ".helm.fullname" . }}-startup"
data:
  {{- if (hasKey .Values.startUp "fileContent") }}
  configdata.sql: |
{{ .Values.startUp.fileContent | indent 4 }}
  {{ else }}
  configdata.sql: |
    -- radarr
    SELECT 'CREATE DATABASE {{ .Values.global.radarrMainDb }} '
    'WITH '
    'ENCODING = ''UTF8'' '
    'CONNECTION LIMIT = -1 '
    'IS_TEMPLATE = False'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '{{ .Values.global.radarrMainDb }}')\gexec
    ;
    SELECT 'CREATE DATABASE {{ .Values.global.radarrLogDb }} '
    'WITH '
    'ENCODING = ''UTF8'' '
    'CONNECTION LIMIT = -1 '
    'IS_TEMPLATE = False'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '{{ .Values.global.radarrLogDb }}')\gexec
    ;
    -- bazarr
    SELECT 'CREATE DATABASE {{ .Values.global.bazarrDb }} '
    'WITH '
    'ENCODING = ''UTF8'' '
    'CONNECTION LIMIT = -1 '
    'IS_TEMPLATE = False'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '{{ .Values.global.bazarrDb }}')\gexec
    ;
    -- authelia
    SELECT 'CREATE DATABASE authelia '
    'WITH '
    'ENCODING = ''UTF8'' '
    'CONNECTION LIMIT = -1 '
    'IS_TEMPLATE = False'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'authelia')\gexec
    ;

    -- We need this uuid extension (in public schema) so we can default the creation of a uuid value on insert
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

    \connect authelia

    do $$
    BEGIN
      IF NOT EXISTS (
          SELECT FROM pg_catalog.pg_roles
          WHERE  rolname = 'authelia') THEN
          BEGIN
            CREATE ROLE "authelia" WITH
                LOGIN
                NOSUPERUSER
                NOCREATEDB
                NOCREATEROLE
                INHERIT
                NOREPLICATION
                NOBYPASSRLS
                CONNECTION LIMIT -1
                PASSWORD '{{ .Values.global.postgresPassword }}';

          EXCEPTION
            WHEN duplicate_object THEN
                NULL;
          END;
      END IF;
    end;
    $$;

    -- Change the owner of the database and public schema to be authelia
    ALTER DATABASE authelia OWNER TO authelia;

  {{- end }}
  {{- if (hasKey .Values.startUp "scriptContent") }}
  configdata.sh: |
{{ .Values.startUp.scriptContent | indent 4 }}
  {{- end }}