fullnameOverride: ombi
image:
  replicaCount: 1
  repository: linuxserver/ombi
  tag: "latest"
  pullPolicy: Always
  containerPort: 3579
  hostname: ombi
  domainPath: "search"
  stripPath: true
  env:
    - name: TZ
      value: UTC
    - name: PGID
      value: 0
    - name: PUID
      value: 0
  volumes:
    storageClassName: nfs-client
    configPath: /config
    configCapacity: 10Mi

serviceAccount:
  create: true
  annotations: {}
  name: "ombi"
  
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80