apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include ".helm.fullname" . }}-startup"
data:
  settings.json: |
    {
      "Authentication": {
        "Username": "",
        "Password": "",
        "PrivateKey": ""
      },
      "ChatClients": {
        "Discord": {
          "BotToken": "",
          "ClientId": "",
          "StatusMessage": "/help",
          "TvShowRoles": [],
          "MovieRoles": [],
          "MonitoredChannels": [],
          "EnableRequestsThroughDirectMessages": false,
          "AutomaticallyNotifyRequesters": true,
          "NotificationMode": "PrivateMessages",
          "NotificationChannels": [],
          "AutomaticallyPurgeCommandMessages": true
        },
        "Language": "english"
      },
      "DownloadClients": {
        "Ombi": {
          "Hostname": "{{ .Values.ombi.fullnameOverride }}",
          "Port": 3579,
          "ApiKey": "${OMBIAPIKEY}",
          "BaseUrl": "/{{ .Values.ombi.fullnameOverride }}",
          "BaseUrl": "",
          "UseSSL": false,
          "Version": "3"
        },
        "Overseerr": {
          "Hostname": "",
          "Port": 5055,
          "ApiKey": "",
          "Movies": {
            "DefaultApiUserID": "",
            "Categories": []
          },
          "TvShows": {
            "DefaultApiUserID": "",
            "Categories": []
          },
          "UseSSL": false,
          "Version": "1"
        },
        "Radarr": {
          "Hostname": "{{ .Values.radarr.fullnameOverride }}",
          "Port": 7878,
          "ApiKey": "${RADARRAPIKEY}",
          "BaseUrl": "/{{ .Values.radarr.fullnameOverride }}",
          "Categories": [
            {
              "Id": 0,
              "Name": "movie",
              "ProfileId": "1",
              "RootFolder": "",
              "MinimumAvailability": "announced",
              "Tags": []
            }
          ],
          "SearchNewRequests": true,
          "MonitorNewRequests": true,
          "UseSSL": false,
          "Version": "3"
        },
        "Sonarr": {
          "Hostname": "{{ .Values.sonarr.fullnameOverride }}",
          "Port": 8989,
          "ApiKey": "${SONARAPIKEY}",
          "BaseUrl": "/{{ .Values.sonarr.fullnameOverride }}",
          "Categories": [
            {
              "Id": 0,
              "Name": "tv",
              "ProfileId": "1",
              "RootFolder": "",
              "Tags": [],
              "LanguageId": "1",
              "UseSeasonFolders": true,
              "SeriesType": "standard"
            }
          ],
          "SearchNewRequests": true,
          "MonitorNewRequests": true,
          "UseSSL": false,
          "Version": "3"
        }
      },
      "BotClient": {
        "Client": ""
      },
      "Movies": {
        "Client": "Disabled"
      },
      "TvShows": {
        "Client": "Disabled",
        "Restrictions": "None"
      },
      "Port": {{ .Values.config.Port }},
      "BaseUrl": "{{ .Values.config.UrlBase }}",
      "DisableAuthentication": false,
      "Version": "2.1.0"
    }
