image:
  repository: haugene/transmission-openvpn
  tag: "latest"
  pullPolicy: Always
  containerPort: 9091
  hostname: transmission

username: YOUR_USERNAME
password: YOUR_PASSWORD

vpn:
  username: YOUR_VPN_USERNAME
  password: YOUR_VPN_PASSWORD
  LOCAL_NETWORK: "10.42.0.0/24" # kubectl describe node | grep CIDRs
  OPENVPN_PROVIDER: PIA
  OPENVPN_CONFIG: YOUR_VPN_REGION # EX https://serverlist.piaservers.net/vpninfo/servers/v6

service:
  type: ClusterIP

securityContext:
  capabilities:
    add: ["NET_ADMIN"]

serviceAccount:
  create: true
  annotations: {}
  name: "transmission"