image:
  repository: lscr.io/linuxserver/transmission
  tag: "latest"
  pullPolicy: Always
  containerPort: 9091
  hostname: transmission
  # env:
  #   - name: TZ
  #     value: UTC
  #   - name: PGID
  #     value: "0"
  #   - name: PUID
  #     value: "0"
  #   - name: TRANSMISSION_WEB_HOME
  #     value: "/kettu/"

username: YOUR_USERNAME
password: YOUR_PASSWORD

vpn:
  username: YOUR_VPN_USERNAME
  password: YOUR_VPN_PASSWORD
  region: us_east # EX us_east, us_west
  connectionStrength: strong

sidecarimage:
  name: pia-vpn
  repository: ghcr.io/xander-rudolph/pia-vpn
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP

serviceAccount:
  create: true
  annotations: {}
  name: "transmission"