apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include ".helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.image.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include ".helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        date: "{{ now | unixEpoch }}"
        {{- include ".helm.selectorLabels" . | nindent 8 }}
    spec:
      hostname: {{ .Values.image.hostname }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include ".helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- if .Values.sidecarimage }}
        - name: "{{ .Values.sidecarimage.name }}"
          image: "{{ .Values.sidecarimage.repository }}:{{ .Values.sidecarimage.tag }}"
          imagePullPolicy: {{ .Values.sidecarimage.pullPolicy }}
        {{- end }}      
        - name: {{ include ".helm.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.env }}
          env: 
            {{- toYaml .Values.image.env | nindent 12 }}
          {{- end }}
          args: [ {{.Values.image.args}} ]
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: books-vol
            mountPath: {{ .Values.image.volumes.booksPath }}
          - name: downloads-vol
            mountPath: {{ .Values.image.volumes.downloadsPath }}
          - name: config-vol
            mountPath: {{ .Values.image.volumes.configPath }}
      volumes:
        - name: books-vol
          persistentVolumeClaim:
            claimName: "{{ Values.image.volumes.booksClaim }}-claim"
        - name: downloads-vol
          persistentVolumeClaim:
            claimName: "{{ Values.image.volumes.downloadsClaim }}-claim"
        - name: config-vol
          persistentVolumeClaim:
            claimName: "{{ include ".helm.fullname" . }}-claim"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
