image:
  repository: lscr.io/linuxserver/prowlarr
  tag: "latest"
  pullPolicy: Always
  containerPort: 9696
  hostname: prowlarr
  # env:
  #   - name: TZ
  #     value: UTC
  #   - name: PGID
  #     value: "0"
  #   - name: PUID
  #     value: "0"

config:
  UrlBase: /prowlarr
  LogLevel: info
  UpdateMechanism: Docker
  BindAddress: "*"
  Port: 9696
  SslPort: 6969
  EnableSsl: False
  LaunchBrowser: True
  AuthenticationMethod: None
  Branch: master
  SslCertPath: 
  SslCertPassword: 
  InstanceName: Prowlarr

service:
  type: ClusterIP

serviceAccount:
  create: true
  annotations: {}
  name: "prowlarr"