apiVersion: v1
kind: Secret
metadata:
  name: "{{ include ".helm.fullname" . }}-secret"
data:
  REDIS_PASSWORD: {{ .Values.global.redisPassword | b64enc }}
stringData:
  REDIS_USER: {{ .Values.global.redisUser }}
  REDIS_PORT: "{{ .Values.redis.containerPort }}"
  REDIS_HOST: {{ .Values.redis.hostname }}
