image:
  repository: lscr.io/linuxserver/overseerr
  tag: "latest"
  pullPolicy: Always
  containerPort: 5055
  hostname: overseerr
  # env:
  #   - name: TZ
  #     value: UTC
  #   - name: PGID
  #     value: "0"
  #   - name: PUID
  #     value: "0"

service:
  type: ClusterIP

serviceAccount:
  create: true
  annotations: {}
  name: "overseerr"