name: Build Docker images

on:
  push:
    branches:
      - main
    paths:
      - ./docker/**

jobs:
  docker-build:
    # uses: ./.github/workflows/docker-publish.yml
    uses: github.com/Xander-Rudolph/.github/.github/workflows/docker-publish.yml@master
    strategy:
      matrix:
        image: ['pia-vpn']
    with:
      image: ${{ matrix.image }}
      # optional
      working_dir: ./docker/${{ matrix.image }}
    secrets: inherit