name: Build Docker images

on:
  workflow_dispatch:
  push:
    paths:
      - ./docker/**
      - ./.github/workflows/Docker build-release.yml
  pull_request:

jobs:
  review:
    if: ${{ github.event_name == 'pull_request' }}
    uses: xander-rudolph/.github/.github/workflows/ollama-pr.yml@main

  docker-build:
    if: ${{ github.event_name != 'pull_request' }}
    uses: xander-rudolph/.github/.github/workflows/docker-publish.yml@main
    strategy:
      matrix:
        image: ['postgres-prep']
    with:
      image_name: ${{ matrix.image }}
      # optional
      working_dir: ./docker/${{ matrix.image }}
      trigger_release: ${{ github.ref_name == 'main' }}
      gitversion: true
    secrets: inherit
