name: Build Docker images

on:
  push:
    branches:
      - main
    paths:
      - ./docker/**

jobs:
  docker-build:
    uses: htaic/.github/.github/workflows/build-docker.yml@main
    strategy:
      matrix:
        image: ['pia-vpn']
    with:
      image: ${{ matrix.image }}
      # optional
      working_dir: ./docker/${{ matrix.image }}
    secrets: inherit