name: Build Docker images

on:
  workflow_dispatch:
  push:
    paths:
      - ./docker/**
      - ./.github/workflows/Docker build-release.yml
  pull_request:

jobs:
  debug:
    permissions: write-all # Check permission when leave comment action failed
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: echo ${{ github.repository_owner }}

  review:
    if: ${{ github.event_name == 'pull_request' }}
    permissions: write-all # Check permission when leave comment action failed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: OpenAI PR Review
        uses: detectiveCrow/ai-review-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#           LANGUAGE: "english"
#           MODEL: "gpt-3.5-turbo"

  docker-build:
    if: ${{ github.event_name != 'pull_request' }}
    uses: xander-rudolph/.github/.github/workflows/docker-publish.yml@master
    strategy:
      matrix:
        image: ['pia-vpn','postgres-prep']
    with:
      image_name: ${{ matrix.image }}
      # optional
      working_dir: ./docker/${{ matrix.image }}
      trigger_release: ${{ github.ref_name == 'main' }}
    secrets: inherit
