name: Update and Release Helm Charts

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  push:
    branches:
      - main
    paths:
      - ./charts/**

jobs:
  update-helm-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Update Helm Dependencies
        run: |
          cd charts
          for chart in */; do
            echo "Updating dependencies for $chart"
            helm dependency update "$chart"
          done

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Helm chart dependencies" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}

  scan-version-bump:
    needs: update-helm-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Helm Linting
        working-directory: charts
        continue-on-error: true
        run: |
          for chart in */; do
            echo "Linting $chart"
            helm lint "$chart"
          done

  release:
    if: github.ref == 'refs/heads/main'
    needs: [update-helm-dependencies, scan-version-bump]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Run Chart Releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
