name: Build Docker images

on:
  pull_request:
    branches:
      - main
    paths:
      - ./docker/*
  push:
    branches:
      - main
    paths:
      - ./docker/*    

jobs:
  docker-build:
    name: Run Docker Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['pia-vpn']
    steps:
      - uses: actions/checkout@v3

      # this should come before any docker type commands to ensure access to the ghcr.io repo for custom images and publishing
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build
        working-directory: "docker/${{ inputs.working_dir }}"
        run: docker build . -t ghcr.io/xander-rudolph/${{}}:$(date +%s) -t ghcr.io/xander-rudolph/${{ matrix.image }}:$GITHUB_REF_NAME -t ghcr.io/xander-rudolph/${{ matrix.image }}:latest

      - name: Upload Artifact - ${{ matrix.image }}
        working-directory: "docker/${{ inputs.working_dir }}"
        run: |
          docker push --all-tags ghcr.io/xander-rudolph/${{ matrix.image }}
        env:
          CR_PAT: "${{ secrets.GITHUB_TOKEN }}"
        continue-on-error: false

