name: Build Docker images

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - ./docker/**
  push:
    # branches:
    #   - main
    # paths:
    #   - ./docker/**   

jobs:
  docker-build:
    name: Run Docker Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['pia-vpn']
    steps:
      - name: Publish docker imagey
        uses: .github/workflows/docker-publish.yml
        with:
          image: ${{ matrix.image }}
          working_dir: ./docker/${{ matrix.image }}
        secrets: inherit
