name: Build Docker images

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - ./docker/**
  push:
    # branches:
    #   - main
    # paths:
    #   - ./docker/**   

jobs:
  docker-build:
    uses: ./.github/workflows/docker-publish.yml
    # uses: https://github.com/Xander-Rudolph/.github/.github/workflows/docker-publish.yml@master
    strategy:
      matrix:
        image: ['pia-vpn']
    with:
      image: ${{ matrix.image }}
      # optional
      working_dir: ./docker/${{ matrix.image }}
    secrets: inherit